#!/usr/bin/env bash
# Skill single-source -> projection compliance.
#
# Contract (governance-diet S1):
#   - .claude/skills is the single canonical skill root (OD-1 resolved).
#   - .agents/skills is a DERIVED provider tree, generated byte-for-byte from
#     .claude/skills (identity transform). It is never hand-maintained.
#   - The skill projection manifest declares an `.agents` projection family and
#     classifies every .agents/skills skill as in-contract or claude_only.
#   - scripts/rev-harness-skill-projection.sh --check enumerates the `.agents`
#     family and fails on any cross-projection drift (missing skill, byte-diff,
#     stale manifest name, or an undeclared on-disk skill).
#
# This test asserts that contract by driving the canonical projection checker,
# rather than re-deriving an independent view of a hand-maintained .agents tree.
set -u

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PROJECTION_CHECK="${REPO_ROOT}/scripts/rev-harness-skill-projection.sh"
MANIFEST="${REPO_ROOT}/.agent/registry/skill_projection_manifest.json"
PASS=0
FAIL=0

record_pass() {
  printf 'PASS: %s\n' "$1"
  PASS=$((PASS + 1))
}

record_fail() {
  printf 'FAIL: %s\n' "$1"
  FAIL=$((FAIL + 1))
}

assert() {
  local condition="$1"
  local message="$2"

  if [[ "${condition}" == "true" ]]; then
    record_pass "${message}"
  else
    record_fail "${message}"
  fi
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    record_fail "required command available: $1"
    return 1
  }
}

require_cmd jq || { printf 'Result: %s passed, %s failed\n' "${PASS}" "${FAIL}"; exit 1; }

# --- Manifest contract assertions -------------------------------------------

[[ -f "${MANIFEST}" ]] \
  && assert true "skill projection manifest exists" \
  || assert false "skill projection manifest exists"

canonical_root="$(jq -r '.canonical_root' "${MANIFEST}" 2>/dev/null)"
[[ "${canonical_root}" == ".claude/skills" ]] \
  && assert true "canonical_root is .claude/skills (OD-1 resolved)" \
  || assert false "canonical_root is .claude/skills (got: ${canonical_root})"

has_agents_family="$(jq -r 'any(.skills[].projections[]?; .provider == "agents")' "${MANIFEST}" 2>/dev/null)"
[[ "${has_agents_family}" == "true" ]] \
  && assert true "manifest declares an .agents projection family" \
  || assert false "manifest declares an .agents projection family"

# Every in-contract skill (claude_only=false) declares an .agents projection;
# every claude_only skill declares none. This is the classification contract.
classification_ok="$(jq -r '
  all(.skills[];
    (.projections | map(.provider) | index("agents") != null) as $has_agents
    | if .claude_only then ($has_agents | not) else $has_agents end)
' "${MANIFEST}" 2>/dev/null)"
[[ "${classification_ok}" == "true" ]] \
  && assert true "every skill is classified in-contract (has .agents projection) or claude_only (none)" \
  || assert false "every skill is classified in-contract or claude_only"

# Every on-disk .agents/skills directory must be declared in-contract in the
# manifest (no hand-maintained orphan trees).
declared_agents="$(jq -r '.skills[] | select(.projections[]?.provider == "agents") | .name' "${MANIFEST}" 2>/dev/null | LC_ALL=C sort -u)"
orphan_found=false
if [[ -d "${REPO_ROOT}/.agents/skills" ]]; then
  while IFS= read -r dir; do
    [[ -n "${dir}" ]] || continue
    name="$(basename "${dir}")"
    if ! grep -Fxq -- "${name}" <<<"${declared_agents}"; then
      orphan_found=true
      printf 'INFO: undeclared .agents/skills/%s (not in-contract in manifest)\n' "${name}"
    fi
  done < <(find "${REPO_ROOT}/.agents/skills" -mindepth 1 -maxdepth 1 -type d | LC_ALL=C sort)
fi
[[ "${orphan_found}" == "false" ]] \
  && assert true "no undeclared (hand-maintained) .agents/skills trees" \
  || assert false "no undeclared (hand-maintained) .agents/skills trees"

# --- Single-source -> projection equivalence (drift gate) -------------------
# Delegate the byte-for-byte parity enforcement (incl. .agents enumeration and
# fail-on-drift behavior) to the canonical projection checker.
#
# --allow-not-installed governs only the codex-installed provider, which
# mirrors a *machine-local* Codex CLI skills directory
# ($CODEX_HOME/skills, default $HOME/.codex/skills) outside this repo. A
# fresh checkout (this repo's own CI runner, or any clone that has never
# run a Codex skill sync) has no such directory, so without this flag the
# check fails on host state this repo does not own instead of on repo
# content. The claude and agents providers -- the two projections that are
# actually part of this repository's tracked tree -- are still enforced at
# full byte-for-byte parity with no relaxation; only the codex-installed
# provider degrades a missing directory to a logged SKIP/WARN
# (scripts/rev-harness-skill-projection.sh reports PASS_NON_ACCEPTANCE, not
# a silent PASS, whenever this happens) and a *stale-but-present* install
# still fails loudly, so this does not hide real projection drift for
# machines that do have Codex skills installed.
if [[ -f "${PROJECTION_CHECK}" ]]; then
  if bash "${PROJECTION_CHECK}" --check --allow-not-installed >/dev/null 2>&1; then
    assert true "rev-harness-skill-projection.sh --check passes (single-source -> projection parity, incl. .agents)"
  else
    assert false "rev-harness-skill-projection.sh --check passes (single-source -> projection parity, incl. .agents)"
  fi
else
  assert false "projection checker present at scripts/rev-harness-skill-projection.sh"
fi

printf '%s\n' "---"
printf 'Result: %s passed, %s failed\n' "${PASS}" "${FAIL}"
[[ "${FAIL}" == "0" ]]
