#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CHECKER="$PROJECT_ROOT/scripts/rev-harness-skill-projection.sh"
TMP_ROOT=""

on_err() {
  local rc=$?
  local line="${BASH_LINENO[0]:-unknown}"
  local command="${BASH_COMMAND:-unknown}"

  printf 'FAIL: unexpected error at line %s: %s (rc=%s)\n' "$line" "$command" "$rc" >&2
  exit "$rc"
}
trap on_err ERR

cleanup() {
  local rc=$?

  rm -rf -- "${TMP_ROOT:-}" 2>/dev/null || true
  exit "$rc"
}
trap cleanup EXIT

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}

contains() {
  local haystack="$1"
  local needle="$2"

  [[ "$haystack" == *"$needle"* ]]
}

assert_json_field() {
  local json="$1"
  local filter="$2"
  local expected="$3"
  local actual=""

  actual="$(printf '%s' "$json" | jq -r "$filter")"
  [[ "$actual" == "$expected" ]] || fail "expected $filter to be $expected, got $actual"
}

setup_fixture() {
  local root="$1"
  shift || true
  local skip_claude=false
  local skip_claude_skill_md=false
  local skip_agents=false
  local skip_installed=false
  local option=""

  for option in "$@"; do
    case "$option" in
      skip-claude) skip_claude=true ;;
      skip-claude-skill-md) skip_claude_skill_md=true ;;
      skip-agents) skip_agents=true ;;
      skip-installed) skip_installed=true ;;
      *) fail "unknown setup_fixture option: $option" ;;
    esac
  done

  # Schema 3: .claude/skills is the canonical source; .agents/skills and
  # $CODEX_HOME/skills are byte-for-byte derived (identity transform) trees.
  mkdir -p \
    "$root/.agent/registry" \
    "$root/.claude/skills" \
    "$root/.agents/skills" \
    "$root/codex-home/skills"

  if [[ "$skip_claude" != true ]]; then
    if [[ "$skip_claude_skill_md" == true ]]; then
      mkdir -p "$root/.claude/skills/example-skill/references"
      printf '%s\n' 'reference body' \
        >"$root/.claude/skills/example-skill/references/reference.md"
    else
      mkdir -p "$root/.claude/skills/example-skill/references"
      printf '%s\n' '---' 'name: example-skill' 'description: Example loader-compliant skill.' '---' '# Example Skill' \
        >"$root/.claude/skills/example-skill/SKILL.md"
      printf '%s\n' 'reference body' \
        >"$root/.claude/skills/example-skill/references/reference.md"
    fi
  fi
  if [[ "$skip_agents" != true && -d "$root/.claude/skills/example-skill" ]]; then
    cp -R "$root/.claude/skills/example-skill" "$root/.agents/skills/example-skill"
  fi
  if [[ "$skip_installed" != true && -d "$root/.claude/skills/example-skill" ]]; then
    cp -R "$root/.claude/skills/example-skill" "$root/codex-home/skills/example-skill"
  fi

  printf '%s\n' \
    '{' \
    '  "schema_version": 3,' \
    '  "canonical_root": ".claude/skills",' \
    '  "documented_transform": {' \
    '    "agents": "identity (byte-for-byte copy of .claude/skills/<skill>; no text substitution)."' \
    '  },' \
    '  "classification_rule": "In-contract skills declare an .agents projection; claude_only skills declare none.",' \
    '  "loader_contract": {' \
    '    "required_file": "SKILL.md",' \
    '    "allowed_frontmatter_keys": ["name", "description"],' \
    '    "allowed_root_entries": ["SKILL.md", "agents", "assets", "references", "scripts"],' \
    '    "install_boundary": "Installed Codex projections must exist at $CODEX_HOME/skills/<skill-name> and match byte-for-byte where declared."' \
    '  },' \
    '  "skills": [' \
    '    {' \
    '      "name": "example-skill",' \
    '      "claude_only": false,' \
    '      "canonical_source": {' \
    '        "path": ".claude/skills/example-skill",' \
    '        "role": "canonical-source"' \
    '      },' \
    '      "projections": [' \
    '        {' \
    '          "provider": "claude",' \
    '          "path": ".claude/skills/example-skill",' \
    '          "projection_kind": "byte-for-byte",' \
    '          "excluded_generated_metadata": [],' \
    '          "activation": {' \
    '            "status": "project-local-active",' \
    '            "auto_discoverable": true,' \
    '            "install_target": ".claude/skills/example-skill",' \
    '            "note": "Claude Code project-local canonical skill."' \
    '          }' \
    '        },' \
    '        {' \
    '          "provider": "agents",' \
    '          "path": ".agents/skills/example-skill",' \
    '          "projection_kind": "byte-for-byte",' \
    '          "excluded_generated_metadata": [],' \
    '          "activation": {' \
    '            "status": "project-local-active",' \
    '            "auto_discoverable": true,' \
    '            "install_target": ".agents/skills/example-skill",' \
    '            "note": "Derived provider tree generated byte-for-byte from .claude/skills."' \
    '          }' \
    '        },' \
    '        {' \
    '          "provider": "codex-installed",' \
    '          "path": "$CODEX_HOME/skills/example-skill",' \
    '          "projection_kind": "byte-for-byte",' \
    '          "excluded_generated_metadata": [],' \
    '          "activation": {' \
    '            "status": "installed-active",' \
    '            "auto_discoverable": true,' \
    '            "install_target": "$CODEX_HOME/skills/example-skill",' \
    '            "note": "Actual Codex skill home projection."' \
    '          }' \
    '        }' \
    '      ]' \
    '    }' \
    '  ]' \
    '}' >"$root/.agent/registry/skill_projection_manifest.json"
}

run_checker_for_root() {
  local root="$1"
  shift

  CODEX_HOME="$root/codex-home" bash "$CHECKER" --root "$root" "$@"
}

test_current_rustskills_paths_pass() {
  local output=""

  output="$(cd "$PROJECT_ROOT" && bash "$CHECKER" --check --json)"

  assert_json_field "$output" '.status' "PASS"
  assert_json_field "$output" '.mode' "acceptance"
  assert_json_field "$output" '.acceptance_eligible' "true"
  assert_json_field "$output" '.allow_not_installed' "false"
  assert_json_field "$output" '.canonical_root' ".claude/skills"
  # Schema 3: every canonical .claude/skills skill is in-contract and declares
  # at least a "claude" and an "agents" projection. rust-skills-knowledge-pack
  # is the canonical Rust skill name (the rustskills-architecture-legacy skill was
  # retired and removed).
  assert_json_field "$output" 'any(.sources[]; .skill == "rust-skills-knowledge-pack" and .status == "PASS")' "true"
  assert_json_field "$output" '([.projections[] | select(.skill == "rust-skills-knowledge-pack") | .provider] | sort | unique | join(","))' "agents,claude,codex-installed"
  assert_json_field "$output" 'all(.projections[]; .projection_kind == "byte-for-byte")' "true"
  assert_json_field "$output" 'any(.projections[]; .provider == "codex-generated")' "false"
  assert_json_field "$output" 'all(.projections[] | select(.provider == "agents"); .activation_status == "project-local-active" and .auto_discoverable == true)' "true"
  assert_json_field "$output" 'all(.projections[] | select(.provider == "codex-installed"); .activation_status == "installed-active")' "true"
  assert_json_field "$output" 'all(.projections[] | select(.provider == "codex-installed"); .auto_discoverable == true)' "true"
  # Every in-contract skill has an .agents projection (no claude_only skills today).
  assert_json_field "$output" '(.projections | map(select(.provider == "agents")) | length) == (.sources | length)' "true"
  assert_json_field "$output" '.warnings | length' "0"
}

test_fixture_passes_with_text_output() {
  local root="$TMP_ROOT/pass"
  local output=""

  setup_fixture "$root"
  output="$(run_checker_for_root "$root" --check)"

  contains "$output" "PASS: skill projection check" \
    || fail "text output should report pass"
  contains "$output" "PASS: example-skill projection claude" \
    || fail "text output should include claude projection"
  contains "$output" "PASS: example-skill projection agents" \
    || fail "text output should include agents projection"
  contains "$output" "PASS: example-skill projection codex-installed" \
    || fail "text output should include installed codex projection"
  [[ "$output" != *"WARN:"* ]] || fail "text output should not warn when installed projection is present"
}

test_fixture_mismatch_fails_closed() {
  local root="$TMP_ROOT/mismatch"
  local stdout_file="$TMP_ROOT/mismatch.out"
  local stderr_file="$TMP_ROOT/mismatch.err"

  # Schema 3: .claude/skills is the canonical source. Drifting it (without
  # regenerating the derived trees) must surface as a mismatch on the derived
  # projections (agents / codex-installed), which no longer equal the source.
  setup_fixture "$root"
  printf '%s\n' 'projection drift' >>"$root/.claude/skills/example-skill/SKILL.md"

  if run_checker_for_root "$root" --check >"$stdout_file" 2>"$stderr_file"; then
    fail "mismatched projection should fail"
  fi

  [[ ! -s "$stdout_file" ]] || fail "mismatch failure should not write stdout in text mode"
  contains "$(cat "$stderr_file")" "inventory/hash mismatch" \
    || fail "mismatch failure should explain inventory/hash mismatch"
  contains "$(cat "$stderr_file")" "projection:example-skill:agents" \
    || fail "mismatch failure should name the drifted derived projection"
}

test_fixture_missing_projection_fails_closed() {
  local root="$TMP_ROOT/missing"
  local stdout_file="$TMP_ROOT/missing.out"
  local stderr_file="$TMP_ROOT/missing.err"

  # Schema 3: a declared in-contract .agents projection whose tree is absent must
  # fail closed (the drift the parity gate exists to catch).
  setup_fixture "$root" skip-agents

  if run_checker_for_root "$root" --check >"$stdout_file" 2>"$stderr_file"; then
    fail "missing projection should fail"
  fi

  [[ ! -s "$stdout_file" ]] || fail "missing path failure should not write stdout in text mode"
  contains "$(cat "$stderr_file")" "missing directory" \
    || fail "missing path failure should explain missing directory"
  contains "$(cat "$stderr_file")" ".agents/skills/example-skill" \
    || fail "missing path failure should name the missing .agents projection path"
}

test_fixture_missing_skill_md_fails_closed() {
  local root="$TMP_ROOT/missing-skill-md"
  local stdout_file="$TMP_ROOT/missing-skill-md.out"
  local stderr_file="$TMP_ROOT/missing-skill-md.err"

  setup_fixture "$root" skip-claude-skill-md

  if run_checker_for_root "$root" --check >"$stdout_file" 2>"$stderr_file"; then
    fail "missing SKILL.md should fail"
  fi

  [[ ! -s "$stdout_file" ]] || fail "missing SKILL.md failure should not write stdout in text mode"
  contains "$(cat "$stderr_file")" "missing SKILL.md" \
    || fail "missing SKILL.md failure should be explicit"
}

# Schema 3 (S1): the .agents tree is a byte-for-byte derived projection. A byte
# diff between the canonical .claude source and the generated .agents tree must
# fail closed as a cross-projection inventory/hash mismatch. (In-contract skills
# may legitimately carry extra root files or frontmatter keys, so anatomy is no
# longer policed; byte-for-byte parity to the canonical source is the contract.)
test_fixture_agents_byte_drift_fails_closed() {
  local root="$TMP_ROOT/agents-byte-drift"
  local stdout_file="$TMP_ROOT/agents-byte-drift.out"
  local stderr_file="$TMP_ROOT/agents-byte-drift.err"

  setup_fixture "$root"
  printf '%s\n' 'agents drift injected' >>"$root/.agents/skills/example-skill/SKILL.md"

  if run_checker_for_root "$root" --check >"$stdout_file" 2>"$stderr_file"; then
    fail "byte drift in the generated .agents tree should fail"
  fi

  [[ ! -s "$stdout_file" ]] || fail "agents byte drift failure should not write stdout in text mode"
  contains "$(cat "$stderr_file")" "inventory/hash mismatch" \
    || fail "agents byte drift failure should explain inventory/hash mismatch"
  contains "$(cat "$stderr_file")" "projection:example-skill:agents" \
    || fail "agents byte drift failure should name the .agents projection"
}

test_fixture_invalid_frontmatter_yaml_fails_closed() {
  local root="$TMP_ROOT/invalid-frontmatter-yaml"
  local stdout_file="$TMP_ROOT/invalid-frontmatter-yaml.out"
  local stderr_file="$TMP_ROOT/invalid-frontmatter-yaml.err"
  local skill_md=""

  # Break the frontmatter fence entirely (drop the opening ---). A SKILL.md with
  # no valid YAML frontmatter block must fail closed.
  setup_fixture "$root"
  for skill_md in \
    "$root/.claude/skills/example-skill/SKILL.md" \
    "$root/.agents/skills/example-skill/SKILL.md" \
    "$root/codex-home/skills/example-skill/SKILL.md"; do
    perl -0pi -e 's/\A---\n//' "$skill_md"
  done

  if run_checker_for_root "$root" --check >"$stdout_file" 2>"$stderr_file"; then
    fail "invalid frontmatter YAML should fail"
  fi

  [[ ! -s "$stdout_file" ]] || fail "frontmatter YAML failure should not write stdout in text mode"
  contains "$(cat "$stderr_file")" "missing or invalid YAML frontmatter" \
    || fail "frontmatter YAML failure should be explicit"
}

test_fixture_missing_description_fails_closed() {
  local root="$TMP_ROOT/missing-description"
  local stdout_file="$TMP_ROOT/missing-description.out"
  local stderr_file="$TMP_ROOT/missing-description.err"
  local skill_md=""

  setup_fixture "$root"
  for skill_md in \
    "$root/.claude/skills/example-skill/SKILL.md" \
    "$root/.agents/skills/example-skill/SKILL.md" \
    "$root/codex-home/skills/example-skill/SKILL.md"; do
    perl -0pi -e 's/description: Example loader-compliant skill\.\n//' "$skill_md"
  done

  if run_checker_for_root "$root" --check >"$stdout_file" 2>"$stderr_file"; then
    fail "missing description should fail"
  fi

  [[ ! -s "$stdout_file" ]] || fail "missing description failure should not write stdout in text mode"
  contains "$(cat "$stderr_file")" "description must be non-empty" \
    || fail "missing description failure should be explicit"
}

test_fixture_folder_name_mismatch_fails_closed() {
  local root="$TMP_ROOT/name-mismatch"
  local stdout_file="$TMP_ROOT/name-mismatch.out"
  local stderr_file="$TMP_ROOT/name-mismatch.err"
  local skill_md=""

  setup_fixture "$root"
  for skill_md in \
    "$root/.claude/skills/example-skill/SKILL.md" \
    "$root/.agents/skills/example-skill/SKILL.md" \
    "$root/codex-home/skills/example-skill/SKILL.md"; do
    perl -0pi -e 's/name: example-skill/name: other-skill/' "$skill_md"
  done

  if run_checker_for_root "$root" --check >"$stdout_file" 2>"$stderr_file"; then
    fail "frontmatter/folder name mismatch should fail"
  fi

  [[ ! -s "$stdout_file" ]] || fail "name mismatch failure should not write stdout in text mode"
  contains "$(cat "$stderr_file")" "frontmatter name does not match expected skill" \
    || fail "name mismatch failure should be explicit"
}

# Schema 3 (S1): the parity gate enumerates the on-disk .agents/skills family and
# fails closed on any skill directory not declared in-contract in the manifest.
# This is what stops a renamed/undeclared .agents tree from silently drifting back.
test_fixture_undeclared_agents_skill_fails_closed() {
  local root="$TMP_ROOT/undeclared-agents-skill"
  local stdout_file="$TMP_ROOT/undeclared-agents-skill.out"
  local stderr_file="$TMP_ROOT/undeclared-agents-skill.err"

  setup_fixture "$root"
  mkdir -p "$root/.agents/skills/ghost-skill"
  printf '%s\n' '---' 'name: ghost-skill' 'description: undeclared orphan.' '---' '# Ghost' \
    >"$root/.agents/skills/ghost-skill/SKILL.md"

  if run_checker_for_root "$root" --check >"$stdout_file" 2>"$stderr_file"; then
    fail "undeclared on-disk .agents skill should fail"
  fi

  [[ ! -s "$stdout_file" ]] || fail "undeclared .agents skill failure should not write stdout in text mode"
  contains "$(cat "$stderr_file")" "not declared in-contract for provider" \
    || fail "undeclared .agents skill failure should explain the enumeration miss"
  contains "$(cat "$stderr_file")" ".agents/skills/ghost-skill" \
    || fail "undeclared .agents skill failure should name the orphan path"
}

test_fixture_missing_installed_codex_fails_by_default() {
  local root="$TMP_ROOT/missing-installed-codex"
  local stdout_file="$TMP_ROOT/missing-installed-codex.out"
  local stderr_file="$TMP_ROOT/missing-installed-codex.err"

  setup_fixture "$root" skip-installed

  if run_checker_for_root "$root" --check >"$stdout_file" 2>"$stderr_file"; then
    fail "missing installed Codex projection should fail by default"
  fi

  [[ ! -s "$stdout_file" ]] || fail "missing installed Codex failure should not write stdout in text mode"
  contains "$(cat "$stderr_file")" "missing directory" \
    || fail "missing installed Codex failure should explain missing directory"
  contains "$(cat "$stderr_file")" '$CODEX_HOME/skills/example-skill' \
    || fail "missing installed Codex failure should name the install path"
}

test_fixture_missing_installed_codex_allow_mode_passes_with_warning() {
  local root="$TMP_ROOT/missing-installed-codex-allowed"
  local output=""

  setup_fixture "$root" skip-installed

  output="$(run_checker_for_root "$root" --check --allow-not-installed --json)"

  assert_json_field "$output" '.status' "PASS_NON_ACCEPTANCE"
  assert_json_field "$output" '.mode' "non-acceptance"
  assert_json_field "$output" '.acceptance_eligible' "false"
  assert_json_field "$output" '.allow_not_installed' "true"
  assert_json_field "$output" '.projections[] | select(.provider == "codex-installed") | .status' "SKIP_NOT_INSTALLED"
  assert_json_field "$output" '.warnings | length' "1"
}

# Schema 3: an installed-active projection that claims it is not auto-discoverable
# violates the activation contract and must fail closed. (Replaces the retired
# codex-generated/install-required activation check; that provider no longer exists.)
test_fixture_installed_active_non_discoverable_fails_closed() {
  local root="$TMP_ROOT/installed-active-non-discoverable"
  local stdout_file="$TMP_ROOT/installed-active-non-discoverable.out"
  local stderr_file="$TMP_ROOT/installed-active-non-discoverable.err"
  local manifest_tmp="$TMP_ROOT/installed-active-non-discoverable-manifest.json"

  setup_fixture "$root"
  # projections[2] is the codex-installed (installed-active) projection.
  jq '
    .skills[0].projections[2].activation.auto_discoverable = false
  ' "$root/.agent/registry/skill_projection_manifest.json" >"$manifest_tmp"
  mv "$manifest_tmp" "$root/.agent/registry/skill_projection_manifest.json"

  if run_checker_for_root "$root" --check >"$stdout_file" 2>"$stderr_file"; then
    fail "installed-active non-discoverable claim should fail"
  fi

  [[ ! -s "$stdout_file" ]] || fail "installed-active non-discoverable failure should not write stdout in text mode"
  contains "$(cat "$stderr_file")" "installed-active projection must be auto-discoverable" \
    || fail "installed-active non-discoverable failure should be explicit"
}

test_fixture_symlink_component_fails_closed() {
  local root="$TMP_ROOT/symlink"
  local stdout_file="$TMP_ROOT/symlink.out"
  local stderr_file="$TMP_ROOT/symlink.err"

  # Build the full fixture, then replace the canonical .claude/skills/example-skill
  # tree with a symlink. A symlinked skill-tree path component must fail closed.
  setup_fixture "$root"
  /bin/rm -rf -- "$root/.claude/skills/example-skill"
  ln -s "$root/.agents/skills/example-skill" "$root/.claude/skills/example-skill"

  if run_checker_for_root "$root" --check >"$stdout_file" 2>"$stderr_file"; then
    fail "symlink path component should fail"
  fi

  [[ ! -s "$stdout_file" ]] || fail "symlink failure should not write stdout in text mode"
  contains "$(cat "$stderr_file")" "symlink path component" \
    || fail "symlink failure should explain symlink path component"
}

test_missing_manifest_fails_closed() {
  local root="$TMP_ROOT/no-manifest"
  local stdout_file="$TMP_ROOT/no-manifest.out"
  local stderr_file="$TMP_ROOT/no-manifest.err"

  mkdir -p "$root"
  if run_checker_for_root "$root" --check >"$stdout_file" 2>"$stderr_file"; then
    fail "missing manifest should fail"
  fi

  [[ ! -s "$stdout_file" ]] || fail "missing manifest should not write stdout"
  contains "$(cat "$stderr_file")" "missing skill projection manifest" \
    || fail "missing manifest failure should be explicit"
}

TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/rev-harness-skill-projection-test.XXXXXX")"

test_current_rustskills_paths_pass
test_fixture_passes_with_text_output
test_fixture_mismatch_fails_closed
test_fixture_missing_projection_fails_closed
test_fixture_missing_skill_md_fails_closed
test_fixture_agents_byte_drift_fails_closed
test_fixture_invalid_frontmatter_yaml_fails_closed
test_fixture_missing_description_fails_closed
test_fixture_folder_name_mismatch_fails_closed
test_fixture_undeclared_agents_skill_fails_closed
test_fixture_missing_installed_codex_fails_by_default
test_fixture_missing_installed_codex_allow_mode_passes_with_warning
test_fixture_installed_active_non_discoverable_fails_closed
test_fixture_symlink_component_fails_closed
test_missing_manifest_fails_closed

printf 'PASS: rev_harness_skill_projection_test\n'
